# Generated by Django 4.0.5 on 2022-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='...'),
        ),
    ]
