# Generated by Django 4.0.5 on 2022-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
